# f=open("gauri.txt","w")
# f.write("GAURI SUDHAKAR PATIL")
# f.close()

# f=open("gauri.txt","r")
# print(f.read())


# file = open("People.txt","r")
# Counter = 0
# a= file.read()
# List =a.split("\n")
# i=0
# for i in List:
#     if i:
#         Counter += 1
          
# print("This is the number of lines in the file")
# print(Counter)

g=open("patil.txt","w")
g.write("my name is GAURI SUDHAKAR PATIL.i am from GIRALE.my college name is S.D.S.M COLLEGE PALGHAR")